### ISSUE TITLE
Does not initialize

### ISSUE THREAD

**Issue by pdesgarets** [JonnyBGod/loopback-include-through-mixin#1]
Hi,
Thanks for this mixin, it is exactly what I was looking for...but it does not work :
I reproduced the issue in a loopback sand box there : https://github.com/pdesgarets/loopback-sandbox

It does not initalize because at 'attached' event, the 'hasMany' relation does not appear in Model.relations. Is it a Loopback issue ? Or a misunderstanding of Loopback API ?

If I log all relations in my repo, I have :
```
Project
{}
Tool
{}
ToolProject
{ project:
   RelationDefinition {
     name: 'project',
     type: 'belongsTo',
     modelFrom: [Object],
     keyFrom: 'projectId',
     modelTo: [Object],
     keyTo: 'id',
     polymorphic: undefined,
     modelThrough: undefined,
     keyThrough: undefined,
     multiple: false,
     properties: {},
     options: {},
     scope: undefined,
     embed: false,
     methods: {} },
  tool:
   RelationDefinition {
     name: 'tool',
     type: 'belongsTo',
     modelFrom: [Object],
     keyFrom: 'toolId',
     modelTo: [Object],
     keyTo: 'id',
     polymorphic: undefined,
     modelThrough: undefined,
     keyThrough: undefined,
     multiple: false,
     properties: {},
     options: {},
     scope: undefined,
     embed: false,
     methods: {} } }
```

Or did I misuse your mixin ?

Thanks

**Comment by JonnyBGod** [comment]
Just release v1.0.1 with a fix for this. It was only working for js defined relations, now should work with relations defined in Json as well.

**Comment by pdesgarets** [comment]
One more fix is needed : you need to check `(relations[targetModel].modelThrough || relations[targetModel].through)` line 10 (the config key in JSON is `through`).
Thanks

**Comment by JonnyBGod** [comment]
Thanks for the fix.
